### ISSUE TITLE
v0.2.0

### ISSUE THREAD

**Issue by jin60641** [jin60641/electron-music-tag-editor#6]
Table
- [ ] context menu로 노출 column on/off 가능
- [ ] 사용자 정의컬럼 기능들 별도 모달에서도 지원) 

<img width="1348" alt="스크린샷 2020-10-07 오전 9 39 09" src="https://user-images.githubusercontent.com/9072743/95274754-a6f7e780-0881-11eb-9e7c-58319cf38b18.png">

- [ ] ctrl, shift 를 통한 다중선택 가능
- [ ] column width조절 가능
- [ ] drag & drop으로 file or folder add(or open. not fixed) 가능
- [ ] filter, search

Editor
- [ ] image drag&drop 으로 업로드 가능
- [ ] image copy&paste 가능
- [ ] image download 가능

Menu
- [ ] undo, redo 지원 (history max는 클수록 좋음)
- [ ] 다국어 지원 (react-i18next 세팅은 완료되어있어서 번역만 추가하면 완료) 
- [ ] 태그 소스 (eg. freedb)

Common
- [ ] encoding 깨짐  (utf8 이슈로 추정)
