### ISSUE TITLE
0.2.0

### ISSUE THREAD

**Issue by jin60641** [jin60641/electron-music-tag-editor#7]
Table

- [x] header -> context menu -> remove column
- [x] ctrl 를 통한 다중선택
- [x] shift 를 통한 다중선택
- [x] column width조절 가능
- [x] sort by, sort direction 지원
- [x] column resize handler 더블 클릭시 maximum content width에 fit하게 조절
- [x] drag & drop으로 file or folder add 가능
- [x] keyboard 로 커서이동, 셀렉트, remove 지원

Editor

- [x]  image drag&drop 으로 업로드 가능
- [x]  image copy&paste 가능
- [x]  image download 가능

Common

- [x] load&save 시 progress 추가
- [x] 개발환경 정리 (hot loader 적용, npm script 개선) @purelledhand ✨
- [x] drag & drop style 개선 (dotted animation border)
